### ISSUE TITLE
Over-writing parameter m 

### ISSUE THREAD

**Issue by annakrystalli** [annakrystalli/CAMPSITE#2]
Here, the supplied parameter `m` is being overwritten. Is that intentional? 

https://github.com/annakrystalli/CAMPSITE/blob/560f8b5aa08820b16d73c22356d0524d606e9e28/R/sim_CAMPSITE.R#L16-L18

**Comment by annakrystalli** [comment]
@alexsla

**Comment by alexsla** [comment]
Yes, that's intentional, to scale m by the selected step size.

**Comment by annakrystalli** [comment]
Great thanks!
